name: Hello World
on: [push]

jobs:
  hello:
    runs-on: [self-hosted]
    steps:
      - run: |
          START=$(date +%s%3N)
          echo "Hello World from Acumen Nomad runner!"
          END=$(date +%s%3N)
          echo "Latency: $((END-START)) ms"